version: "3"
services:
  gitbook_wiki:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_gitbook
    hostname: gitbook
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
      - "35729:35729"
    volumes:
      - .:/gitbook
    environment:
      BOOK_URL: https://gitee.com/0616/ld-help.git
    command: ['/gitbook/start.sh']

