version: "3"
services:
  gitbook_wiki:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hdy_gitbook
    hostname: gitbook
    restart: always
    ports:
      - "4002:4002"
      - "4003:4003"
      - "35730:35730"
    volumes:
      - .:/gitbook
    environment:
      BOOK_URL: https://gitee.com/0616/ld-help.git
    command: ['/gitbook/start.sh']

